[package]
name = "syfala_network"
version = "0.1.0"
edition = "2024"

[dependencies]

syfala_proto = { path = "../syfala_proto" }
serde = { version = "1", default-features = false, features = [
    "derive",
    "alloc",
] }
