[package]
name = "syfala_jack"
version = "0.1.0"
edition = "2024"

[dependencies]

syfala_utils = { path = "../syfala_utils" }
jack = "0.13"
syfala_proto = { path = "../syfala_proto" }

[dev-dependencies]
syfala_network = { path = "../syfala_network" }
rustc-hash = { version = "2" }
